# Generated by Django 5.2.17 on 2026-09-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
